name: D4L Publish Artifact

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:

    inputs:
      branchName:
        description: 'Name of the Branch to checkout'
        required: false
        default: 'master'

    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          ref: ${{ INPUT_BRANCHNAME }}
      - name: Cleanup
        run: ./gradlew clean
      - name: Build project
        run: ./gradlew build
      - name: Publish artifacts
        run: ./gradlew publish

